# Teaching NumPy with Jupyter Notebook

### 1. Importing NumPy

In [21]:
import numpy as np

### 2. Creating Arrays

In [37]:
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [49]:
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

### 3. Array Attributes

In [44]:
# Get the shape of the array
array_2d.shape

(3, 3)

In [45]:
# Get the number of dimensions of the array
array_2d.ndim

2

In [42]:
# Get the data type of the array elements
array_2d.dtype

dtype('int64')

### 4. Array Indexing and Slicing

In [48]:
# Indexing a 1D array
array_1d[2]

np.int64(3)

In [51]:
# Indexing a 2D array
array_2d[0, 2]

np.int64(3)

In [52]:
# Slicing a 1D array
array_1d[1:4]

array([2, 3, 4])

In [54]:
# Slicing a 2D array
array_2d[:, 1:3]

array([[2, 3],
       [5, 6]])

### 5. Array Operations

In [30]:
# Element-wise addition
array_1d + 10

array([11, 12, 13, 14, 15])

In [31]:
# Element-wise multiplication
array_2d * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
# Dot product
array_1d.dot(array_1d)

np.int64(55)

In [33]:
# Matrix multiplication
array_2d.dot(array_2d.T)

array([[14, 32],
       [32, 77]])

### 6. Universal Functions

In [34]:
# Applying a universal function
np.sqrt(array_1d)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [35]:
# Applying a universal function on 2D array
np.exp(array_2d)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

### 7. Array Aggregation

In [7]:
# Sum of array elements
np.sum(array_1d)

# Mean of array elements
np.mean(array_2d)

# Standard deviation of array elements
np.std(array_2d)

np.float64(1.707825127659933)

### 8. Reshaping Arrays

In [8]:
# Reshape 1D array to 2D array
array_reshaped = array_1d.reshape((5, 1))
array_reshaped

# Flatten a 2D array to 1D
array_flattened = array_2d.flatten()
array_flattened

array([1, 2, 3, 4, 5, 6])

### 9. Stacking Arrays

In [9]:
# Vertical stack
array_vstack = np.vstack([array_1d, array_1d])
array_vstack

# Horizontal stack
array_hstack = np.hstack([array_2d, array_2d])
array_hstack

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### 10. Splitting Arrays

In [10]:
# Split 1D array into 3 parts
array_split = np.array_split(array_1d, 3)
array_split

# Split 2D array into 2 parts along the second axis
array_split_2d = np.array_split(array_2d, 2, axis=1)
array_split_2d

[array([[1, 2],
        [4, 5]]),
 array([[3],
        [6]])]

### 11. Broadcasting

In [11]:
# Broadcasting example
array_broadcast = array_2d + array_1d[:3]
array_broadcast

array([[2, 4, 6],
       [5, 7, 9]])

### 12. Boolean Indexing

In [12]:
# Boolean indexing example
bool_idx = array_1d > 2
filtered_array = array_1d[bool_idx]
filtered_array

array([3, 4, 5])

### 13. Fancy Indexing

In [13]:
# Fancy indexing example
fancy_idx = [0, 2, 4]
fancy_array = array_1d[fancy_idx]
fancy_array

array([1, 3, 5])

### 14. np.where()

In [14]:
# np.where example
where_array = np.where(array_1d > 2, array_1d, -1)
where_array

array([-1, -1,  3,  4,  5])

### 15. np.unique()

In [15]:
# np.unique example
unique_array = np.unique(array_1d)
unique_array

array([1, 2, 3, 4, 5])

### 16. np.concatenate()

In [16]:
# np.concatenate example
concat_array = np.concatenate((array_1d, array_1d))
concat_array

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

### 17. np.stack()

In [17]:
# np.stack example
stack_array = np.stack((array_1d, array_1d))
stack_array

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

### 18. np.tile()

In [18]:
# np.tile example
tile_array = np.tile(array_1d, 2)
tile_array

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

### 19. np.repeat()

In [19]:
# np.repeat example
repeat_array = np.repeat(array_1d, 2)
repeat_array

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

### 20. np.linspace()

In [20]:
# np.linspace example
linspace_array = np.linspace(0, 10, 5)
linspace_array

array([ 0. ,  2.5,  5. ,  7.5, 10. ])